#!/bin/sh

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

# Create workspaces
bspc monitor -d 1 2 3 4
